{{- if .Values.authentication.deploySecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.authentication.secret }}
stringData:
  client-id: {{ .Values.authentication.username }}
  {{ .Values.authentication.passwordKey }}: {{ .Values.authentication.password }}
type: Opaque
{{ end }}