apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: {{ include "retail-db.name" . }}
    app.openshift.io/runtime: postgresql
  name: {{ include "retail-db.name" . }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "retail-db.name" . }}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: {{ include "retail-db.name" . }}
        name: {{ include "retail-db.name" . }}
    spec:
      containers:
        - image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          name: {{ include "retail-db.name" . }}
          ports:
            - name: postgresql
              containerPort: 5432
              protocol: TCP
          resources: {}
          env:
            - name: POSTGRESQL_USER
              value: {{ .Values.pgsqlUser }}
            - name: POSTGRESQL_PASSWORD
              value: {{ .Values.pgsqlPassword }}
            - name: POSTGRESQL_ADMIN_PASSWORD
              value: {{ .Values.pgsqlAdminPassword }}
            - name: POSTGRESQL_DATABASE
              value: {{ .Values.pgsqlDatabase }}
          {{- if eq .Values.persistence.mode "persistent" }}
          volumeMounts:
            - name: "{{ include "retail-db.name" . }}-data"
              mountPath: "/var/lib/pgsql/data"
              volumes:
          {{- end }}
      {{- if eq .Values.persistence.mode "persistent" }}
      volumes:
        - name: "{{ include "retail-db.name" . }}-data"
          persistentVolumeClaim:
            claimName: {{ include "retail-db.name" . }}
      {{- end }}
      serviceAccountName: {{ include "retail-db.serviceAccountName" . }}
      serviceAccount: {{ include "retail-db.serviceAccountName" . }}
