apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    {{- include "retail-db.labels" . | nindent 4 }}
    app.openshift.io/runtime: postgresql    
  name: {{ include "retail-db.name" . }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "retail-db.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        {{- include "retail-db.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          name: {{ include "retail-db.name" . }}
          ports:
            - name: postgresql
              containerPort: 5432
              protocol: TCP
          resources: {}
          env:
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "retail-db.name" . }}
                  key: database-user
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "retail-db.name" . }}
                  key: database-password
            - name: POSTGRESQL_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "retail-db.name" . }}
                  key: database-admin-password
            - name: POSTGRESQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ include "retail-db.name" . }}
                  key: database-name
          {{- if eq .Values.persistence.mode "persistent" }}
          volumeMounts:
            - name: "{{ include "retail-db.name" . }}-data"
              mountPath: "/var/lib/pgsql/data"
              volumes:
          {{- end }}
      {{- if eq .Values.persistence.mode "persistent" }}
      volumes:
        - name: "{{ include "retail-db.name" . }}-data"
          persistentVolumeClaim:
            claimName: {{ include "retail-db.name" . }}
      {{- end }}
      serviceAccountName: {{ include "retail-db.serviceAccountName" . }}
      serviceAccount: {{ include "retail-db.serviceAccountName" . }}
