{{- if eq .Values.persistence.mode "persistent" -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "retail-db.name" . }}
  labels:
    {{- include "retail-db.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.capacity }}
{{- end }}