apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: {{ include "retail-db.name" . }}
  name: {{ include "retail-db.name" . }}
spec:
  ports:
    - name: postgresql
      protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app.kubernetes.io/name: {{ include "retail-db.name" . }}
