apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "retail-db.labels" . | nindent 4 }}
  name: {{ include "retail-db.name" . }}
spec:
  ports:
    - name: postgresql
      protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    {{- include "retail-db.selectorLabels" . | nindent 4 }}
