name: cashback-db
replicas: 1
image: quay.io/solution-pattern-cdc/cashback-db:1.0
imagePullPolicy: IfNotPresent
pgsqlUser: cashback
pgsqlPassword: cashback
pgsqlAdminPassword: password
pgsqlDatabase: cashback
persistence:
  mode: persistent
  capacity: 5Gi
serviceAccount:
  create: true
