name: cashback-db
replicas: 1
image: quay.io/solution-pattern-cdc/cashback-db:ed80f7b
imagePullPolicy: IfNotPresent
pgsqlUser: retail
pgsqlPassword: retail
pgsqlAdminPassword: password
pgsqlDatabase: cashback
persistence:
  mode: persistent
  capacity: 5Gi
serviceAccount:
  create: true
