name: search-service
replicas: 1
image: quay.io/solution-pattern-cdc/search-service:8af7a1c
imagePullPolicy: IfNotPresent

ports:
  http:
    name: http
    port: 8080

resources: {}

livenessProbe:
  httpGet:
    path: /q/health/live
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 3

readinessProbe:
  httpGet:
    path: /q/health/ready
    port: http
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 3

serviceAccount:
  create: true

service:
  type: ClusterIP
  port: 8080
  portName: http

route:
  enabled: true
  host:
  tlsEnabled: true
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect

elasticsearch:
  hosts:
  username:
  password:
  protocol: http
  index: products
