name: cashback-connector
replicas: 1
image: quay.io/solution-pattern-cdc/cashback-connector:9013475
imagePullPolicy: IfNotPresent

ports:
  http:
    name: http
    port: 8080

resources: 
  limits:
    cpu: 250m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  httpGet:
    path: /q/health/live
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 3

readinessProbe:
  httpGet:
    path: /q/health/ready
    port: http
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 3

serviceAccount:
  create: true

kafka:
  bootstrapServer: ""
  securityProtocol: ""
  saslMechanism: ""
  userId: ""
  password: ""
  topics:
    customer: retail.updates.public.customer
    sale: retail.sale-aggregated
  consumerGroup: cashback-connector

postgresql:
  host: ""
  username: ""
  password: ""
  database: ""
  