name: cashback-connector
replicas: 1
image: quay.io/solution-pattern-cdc/cashback-connector:9013475
imagePullPolicy: IfNotPresent

ports:
  http:
    name: http
    port: 8080

resources: {}

livenessProbe:
  httpGet:
    path: /q/health/live
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 3

readinessProbe:
  httpGet:
    path: /q/health/ready
    port: http
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 3

serviceAccount:
  create: true

service:
  type: ClusterIP
  port: 8080
  portName: http

kafka:
  bootstrapServer: ""
  securityProtocol: ""
  saslMechanism: ""
  userId: ""
  password: ""
  topics:
    customer: retail.updates.public.customer
    sale: retail.sale-aggregated
  consumerGroup: cashback-connector

postgresql:
  host: ""
  username: ""
  password: ""
  database: ""
  