apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    {{- include "retail-simulation.labels" . | nindent 4 }}
    app.openshift.io/runtime: camel    
  name: {{ include "retail-simulation.name" . }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "retail-simulation.selectorLabels" . | nindent 6 }}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        {{- include "retail-simulation.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          name: {{ include "retail-simulation.name" . }}
          ports:
            - name: {{ .Values.ports.http.name }}
              containerPort: {{ .Values.ports.http.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          volumeMounts:
            - mountPath: /deployments/config
              name: config
      serviceAccountName: {{ include "retail-simulation.serviceAccountName" . }}
      serviceAccount: {{ include "retail-simulation.serviceAccountName" . }}
      volumes:
        - name: config
          secret:
            secretName: {{ include "retail-simulation.name" . }}