apiVersion: v1
kind: Service
metadata:
  name: {{ include "retail-simulation.name" . }}
  labels:
    {{- include "retail-simulation.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.ports.http.name }}
      protocol: TCP
      name: {{ .Values.service.portName }}
  selector:
    {{- include "retail-simulation.selectorLabels" . | nindent 4 }}
