kind: Secret
apiVersion: v1
metadata:
  name: {{ include "cashback-db.name" . }}
  labels:
    {{- include "cashback-db.labels" . | nindent 4 }}
stringData:
  database-user: {{ .Values.pgsqlUser }}
  database-password: {{ .Values.pgsqlPassword }}
  database-admin-password: {{ .Values.pgsqlAdminPassword }}
  database-name: {{ .Values.pgsqlDatabase }}
type: Opaque