{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cashback-db.name" . }}
  labels:
    {{- include "cashback-db.labels" . | nindent 4 }}
{{- end }}
